; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-supermini
framework = arduino
monitor_speed = 115200
build_flags = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D PIN_STEP=10
	-D PIN_DIR=4
lib_deps = 
	fastled/FastLED @ ^3.9.15
	waspinator/AccelStepper @ ^1.64.0
	arduino-libraries/Stepper@^1.1.3

[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-supermini
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-D PIN_STEP=9
	-D PIN_DIR=8
lib_deps = 
	fastled/FastLED @ ^3.9.15
	waspinator/AccelStepper @ ^1.64.0
	arduino-libraries/Stepper@^1.1.3

[env:malibotti_stepper_v1]
platform = espressif32
board = malibotti_stepper_v1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	waspinator/AccelStepper @ ^1.64.0
